# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionNumber',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], default='1', help_text='Statement Number'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Enter your Statement', max_length=300),
        ),
    ]
