# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0002_auto_20180107_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionNumber',
        ),
        migrations.AddField(
            model_name='question',
            name='statementNumber',
            field=models.IntegerField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], default='1'),
        ),
    ]
