# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-05 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0005_auto_20180107_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 21, 44, 12, 251724, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Enter your Statement', max_length=500),
        ),
    ]
