# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-09 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0006_auto_20180205_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statementNumber',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='1', verbose_name='The number of the statement'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Enter your text', max_length=500, verbose_name='New Statement'),
        ),
    ]
