# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-11 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MC', '0007_auto_20180209_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statementNumber', models.IntegerField(default='1', verbose_name='The number of the statement')),
                ('date_created', models.DateTimeField()),
                ('onepk', models.IntegerField(default='1')),
                ('twopk', models.IntegerField(default='1')),
                ('threepk', models.IntegerField(default='1')),
                ('fourpk', models.IntegerField(default='1')),
                ('fivepk', models.IntegerField(default='1')),
                ('oneScore', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='')),
                ('twoScore', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='1', verbose_name='')),
                ('threeScore', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='1', verbose_name='')),
                ('fourScore', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='1', verbose_name='')),
                ('fiveScore', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='1', verbose_name='')),
                ('bigScore', models.IntegerField(choices=[(0, 'Really Bad'), (1, 'Poorly'), (2, 'Ok'), (3, 'Pretty Good'), (4, 'Really Good')], default='1', verbose_name='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
