# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-11 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0008_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='bigScore',
            field=models.IntegerField(choices=[(0, 'Really Bad'), (1, 'Poorly'), (2, 'Ok'), (3, 'Pretty Good'), (4, 'Really Good')], default='3', verbose_name='How are you feeling over the past week?'),
        ),
        migrations.AlterField(
            model_name='score',
            name='fiveScore',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='none', verbose_name='statement 5'),
        ),
        migrations.AlterField(
            model_name='score',
            name='fourScore',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='none', verbose_name='statement 4'),
        ),
        migrations.AlterField(
            model_name='score',
            name='oneScore',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='none', verbose_name='statement 1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='threeScore',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='none', verbose_name='statement 3'),
        ),
        migrations.AlterField(
            model_name='score',
            name='twoScore',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='none', verbose_name='statement 2'),
        ),
    ]
