# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0009_auto_20180211_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='oneScore',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default='none'),
        ),
    ]
