# Generated by Django 2.0.2 on 2018-02-24 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0010_auto_20180215_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='bigScore',
            field=models.IntegerField(choices=[(0, 'Really Bad'), (1, 'Poorly'), (2, 'Ok'), (3, 'Pretty Good'), (4, 'Really Good')], default='3', verbose_name='How were you feeling?'),
        ),
        migrations.AlterField(
            model_name='score',
            name='fiveScore',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='none', verbose_name='statement 5'),
        ),
        migrations.AlterField(
            model_name='score',
            name='fourScore',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='none', verbose_name='statement 4'),
        ),
        migrations.AlterField(
            model_name='score',
            name='oneScore',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='none', verbose_name='statement 1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='threeScore',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='none', verbose_name='statement 3'),
        ),
        migrations.AlterField(
            model_name='score',
            name='twoScore',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='none', verbose_name='statement 2'),
        ),
    ]
