# Generated by Django 2.0.2 on 2018-02-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0011_auto_20180224_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='Enter Your Statement', max_length=500, verbose_name=''),
        ),
    ]
