# Generated by Django 2.0.2 on 2018-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MC', '0012_auto_20180226_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='bigScore',
            field=models.IntegerField(choices=[(0, 'Really Poorly'), (1, 'Poorly'), (2, 'Ok'), (3, 'Good'), (4, 'Really Good')], default='3', verbose_name='How were you feeling?'),
        ),
    ]
